In [14]:
import pandas as pd
import numpy as np

# Задание 1.

## 1.1.

In [23]:
# 1) Создайте объекты Series, используя различные способы 
# питоновские списки
s1 = pd.Series(["M", "F", "F", "M", "F"])
# словарь
s2 = pd.Series({0: 32, 1: 45, 2: 25, 3: 39, 4: 59})
# ndarray
s3 = pd.Series(np.array([5, 3, 3, 3, 2]))
s4 = pd.Series(np.array([4, 5, 5, 3, 2]))
s5 = pd.Series(np.array([5, 2, 5, 4, 1]))
s6 = pd.Series(np.array([5, 5, 5, 3, 2]))
s7 = pd.Series(np.array([5, 5, 2, 4, 1]))

In [25]:
s = np.array([5, 3, 3, 3, 2])
d = {"Gender":s}
df = pd.DataFrame(d)
df

Gender
0       5
1       3
2       3
3       3
4       2

In [16]:
# 2) Вычислить среднее значение Возраста
print(f"Среднее значение Возраста равно {np.mean(s2)}")

Среднее значение Возраста равно 40.0


In [17]:
# 3) Кого больше, мужчин или женщин?
print(f"Женщин всего {len(s1[s1 == 'F'])}, а мужчин {len(s1[s1 == 'M'])}, поэтому женщин больше.")

Женщин всего 3, а мужчин 2, поэтому женщин больше.


## 1.2.

In [18]:
# единый усредненный показатель лояльности к начальству
means = np.mean(np.array([s3,s4,s5,s6,s7]).T, axis = 1)
means

array([4.8, 4. , 4. , 3.4, 1.6])

In [19]:
p = pd.Series(means, s1)
p

M    4.8
F    4.0
F    4.0
M    3.4
F    1.6
dtype: float64

In [20]:
print(f"У женщин средняя степень лояльности {np.round(np.mean(p.loc['F']), 2)}, а у мужчин {np.mean(p.loc['M'])},"
     "поэтому мужчины более лояльны к вышестоящему начальству.")

У женщин средняя степень лояльности 3.2, а у мужчин 4.1,поэтому мужчины более лояльны к вышестоящему начальству.


In [21]:
q = s2.copy()
for i in range(len(q)):
    if q[i] < 40:
        q[i] = "Молодой возраст"
    elif 40 <= q[i] < 50:
        q[i] = "Средний возраст"
    else:
        q[i] = "Пожилой возраст"
p = pd.Series(means, q)
p

Молодой возраст    4.8
Средний возраст    4.0
Молодой возраст    4.0
Молодой возраст    3.4
Пожилой возраст    1.6
dtype: float64

In [22]:
ages = ["Молодой возраст", "Средний возраст", "Пожилой возраст"]
for i in ages:
    print(f"Средняя степень лояльности у {i} составляет {np.round(np.mean(p.loc[i]), 2)}")

Средняя степень лояльности у Молодой возраст составляет 4.07
Средняя степень лояльности у Средний возраст составляет 4.0
Средняя степень лояльности у Пожилой возраст составляет 1.6


Таким образом, молодые люди более лояльны к начальству, чем средние и пожилые, а люди среднего возраста более лояльны, чем пожилого возраста. То есть, наблюдается тенденция: с увеличением возраста лояльность к вышествоящему начальству уменьшается.

## 1.3.

In [263]:
# 1) Создать DataFrame  
d = {"Gender":s1, "Age": s2, "q1": s3, "q2": s4, "q3": s5,"q4": s6,"q5": s7}
df = pd.DataFrame(d)
df

Gender  Age  q1  q2  q3  q4  q5
0      M   32   5   4   5   5   5
1      F   45   3   5   2   5   5
2      F   25   3   5   5   5   2
3      M   39   3   3   4   3   4
4      F   59   2   2   1   2   1

In [264]:
# 2)Кто « полностью согласен» по вопросу q1?  Это мужчина или женщина?
print(df[df.q1 == 5])
print("Полностью согласен по вопросу q1 мужчина")

  Gender  Age  q1  q2  q3  q4  q5
0      M   32   5   4   5   5   5
Полностью согласен по вопросу q1 мужчина


In [287]:
# 3)Есть ли  «не согласные» по вопросу q1?
print(len(df[df.q1 == 1]))
print("Полностью несогласных по вопросу q1 нет")

0
Полностью несогласных по вопросу q1 нет


In [284]:
# 4)По какому вопросу было больше всего «полностью согласных»?
q = ["q1", "q2", "q3", "q4", "q5"]
qmax = 0
m = 0 
for i in q:
    if m < len(df[df[i] == 5]):
        m = len(df[df[i] == 5])
        qmax = i
print(f"По вопросу {qmax} было больше всего 'полностью несогласных'.")

По вопросу q4 было больше всего 'полностью несогласных'.


# Задание 2.

## 1. Сгенерировать массив из положительных чисел произвольной длины. Вывести элементы, которые больше среднего арифметического.

In [34]:
s = np.random.randint(1, 10000, size=10)
s

array([2857,   54, 7234, 3635,  787,  267, 9405,   93, 4188,  705])

In [35]:
s[s > np.mean(s)]

array([7234, 3635, 9405, 4188])

## 2.	Сгенерировать массив из 20 элементов, элементы которого лежат в интервале [0, 10]. Определить количество элементов, отличающихся от минимального на 5. Найти среднее арифметическое всех четных элементов массива, стоящих на нечетных местах.

In [73]:
# генерируем массив из 20 элементов из отрезка [0,10]
s = np.random.randint(0, 11, size=20)
s

array([8, 2, 5, 7, 6, 8, 9, 1, 4, 3, 5, 5, 6, 4, 0, 1, 0, 0, 2, 5])

In [74]:
print(f"Минимальное число в массиве: {np.min(s)}")
print(f"Элементы, отличающиеся от минимального (равного {np.min(s)}) на 5: {s[s - np.min(s) == 5]}")
print(f"Количество элементов, отличающихся от минимального (равного {np.min(s)}) на 5: {len(s[s - np.min(s) == 5])}")

Минимальное число в массиве: 0
Элементы, отличающиеся от минимального (равного 0) на 5: [5 5 5 5]
Количество элементов, отличающихся от минимального (равного 0) на 5: 4


In [75]:
# Элементы массива, стоящие на нечетных местах
s[::2]

array([8, 5, 6, 9, 4, 5, 6, 0, 0, 2])

In [76]:
# Элементы массива, стоящие на нечетных местах, которые являются четными
s[::2][s[::2] % 2 == 0]

array([8, 6, 4, 6, 0, 0, 2])

In [77]:
print("Среднее арифметическое всех четных элементов массива, стоящих на нечетных местах"
      f"равно {np.round(np.mean(s[::2][s[::2] % 2 == 0]), 2)}")

Среднее арифметическое всех четных элементов массива, стоящих на нечетных местахравно 3.71
